apiVersion: v1
kind: ConfigMap
metadata:
  name: ha
data:
  configuration.yaml: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    # Text to speech
    tts:
      - platform: google_translate

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/16
        - 10.243.243.0/24
        - 10.43.0.0/16

    homekit:
    - mode: bridge
      filter:
        include_domains:
          - cover
          - climate
        include_entity_globs:
          #- sensor.nest*
          #- sensor.upstairs*
          #- sensor.nest_temperature

      name: "Home Assistant Bridge"
      port: 21064

    - mode: accessory
      filter:
        include_entities:
          media_player.samsung_tv

      name: "Samsung Frame TV"
      port: 21065

    recorder:
      db_url: !env_var DB_URL
