apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  name: ha
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "home-assistant.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      hostNetwork: true
      containers:
      - env:
        - name: TZ
          value: America/Denver
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: ha-in-timescale
              key: db_url

        image: ghcr.io/michael-odell/home-assistant:main
        #image: ghcr.io/home-assistant/home-assistant:2024.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        name: ha
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        - containerPort: 5353
          name: homekit-tcp
          protocol: TCP
        - containerPort: 21064
          name: homekit-bridge
          protocol: UDP
        - containerPort: 21065
          name: homekit-tv
          protocol: UDP

        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1

        securityContext:
          privileged: null

        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 8123
          timeoutSeconds: 1

        volumeMounts:
        - name: config-persistent
          mountPath: /config/
          readOnly: false

        #- name: configuration-yaml
        #  mountPath: /config/configuration.yaml
        #  readOnly: false
        #  subPath: configuration.yaml

      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: true
      serviceAccountName: default

      volumes:
      - name: config-persistent
        persistentVolumeClaim:
          claimName: ha-config

      - name: configuration-yaml
        configMap:
          name: ha
