apiVersion: v1
kind: Service
metadata:
  name: ha
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: http
  - name: homekit-tcp
    port: 5353
    targetPort: 5353
    protocol: UDP
  - name: homekit-bridge
    port: 21064
    targetPort: 21064
    protocol: UDP
  - name: homekit-tv
    port: 21065
    targetPort: 21065
    protocol: UDP

  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
  type: ClusterIP
